-- Complete Leaderboard Data Insertion - All 172 Teams from the Image
-- This script inserts all teams with their exact data from the leaderboard image

-- Clear existing data (optional - remove if you want to keep existing data)
-- DELETE FROM leaderboard;

-- Insert all 172 teams with their exact data from the image
INSERT INTO leaderboard (team_name, total_members, linkedin_posts, round1_points, team_type, notes) VALUES
-- Teams with 5 points (successful completion)
('404 FOUND', 5, 5, 5, 'VIT', 'Top performing team'),
('3VP (3 Visionary Programmers)', 3, 3, 5, 'VIT', 'Strong performance'),
('404 Coder Not Found', 5, 5, 5, 'VIT', 'Excellent results'),
('404 found', 5, 5, 5, 'VIT', 'Consistent performance'),
('404 Founders', 5, 5, 5, 'VIT', 'Strong team'),
('404 Founders (External)', 3, 3, 5, 'External', 'External team with excellent results'),
('8-BIT', 4, 4, 5, 'VIT', 'Technical excellence'),
('ABC', 5, 5, 5, 'VIT', 'Innovative solutions'),
('Algo evengers', 2, 2, 5, 'VIT', 'Algorithm specialists'),
('Algo Ninjas', 5, 5, 5, 'VIT', 'Algorithm masters'),
('Anjani', 5, 5, 5, 'VIT', 'Strong performance'),
('Beyond Boundaries', 4, 4, 5, 'VIT', 'Boundary pushers'),
('Binary brains', 4, 4, 5, 'VIT', 'Binary experts'),
('Bit Lyfe', 4, 4, 5, 'VIT', 'Bit manipulation specialists'),
('Bit wizards', 3, 3, 5, 'VIT', 'Bit manipulation wizards'),
('Black Knights', 2, 2, 5, 'VIT', 'Elite team'),
('Bob the Builder', 3, 3, 5, 'VIT', 'Building solutions'),
('Bobshacks', 5, 5, 5, 'VIT', 'Hackathon veterans'),
('BUG - SLAYER', 5, 5, 5, 'VIT', 'Bug elimination experts'),
('Bug Buster', 5, 5, 5, 'VIT', 'Bug hunting specialists'),
('BugHiBug', 5, 5, 5, 'VIT', 'Bug resolution team'),
('BugSlayer', 5, 5, 5, 'VIT', 'Bug elimination masters'),
('Chill code club', 5, 5, 5, 'VIT', 'Relaxed coding approach'),
('Code & Chill', 3, 3, 5, 'VIT', 'Chill coding style'),
('Code Cabbit', 1, 1, 5, 'VIT', 'Solo performer'),
('Code Catalyst', 4, 4, 5, 'VIT', 'Catalyst for change'),
('Code Catalysts', 5, 5, 5, 'VIT', 'Change catalysts'),
('Code Clash', 5, 5, 5, 'VIT', 'Competitive coding'),
('Code Commanders', 2, 2, 5, 'VIT', 'Command and control'),
('Code Crew', 5, 5, 5, 'VIT', 'Crew of coders'),
('Code Quest', 5, 5, 5, 'VIT', 'Quest for excellence'),
('Code Rebels', 4, 4, 5, 'VIT', 'Rebellious coding'),
('CODE STORM (external)', 2, 2, 5, 'External', 'External storm team'),
('CODE VIBES', 2, 2, 5, 'VIT', 'Good vibes coding'),
('Code_Rafters', 4, 4, 5, 'VIT', 'Rafting through code'),
('Code2gether', 2, 2, 5, 'VIT', 'Coding together'),
('Code4Cause', 2, 2, 5, 'VIT', 'Coding for a cause'),
('CodeByte', 4, 4, 5, 'VIT', 'Byte-sized solutions'),
('CodeMerners', 4, 4, 5, 'VIT', 'MERN stack experts'),
('Codestorm', 4, 4, 5, 'VIT', 'Storm of code'),
('CodeV', 5, 5, 5, 'VIT', 'Version control masters'),
('Codeverz', 5, 5, 5, 'VIT', 'Code versioning experts'),
('CodeXhunters', 5, 5, 5, 'VIT', 'Code hunters'),
('Code7TN', 5, 5, 5, 'VIT', 'Tennessee coding team'),
('CODING SPARTANS', 5, 5, 5, 'VIT', 'Spartan coding warriors'),
('Codyssey', 5, 5, 5, 'VIT', 'Coding odyssey'),
('coffee codes', 5, 5, 5, 'VIT', 'Coffee-fueled coding'),
('Creative Buddies', 5, 5, 5, 'VIT', 'Creative solutions'),
('CRYPTOXIS', 5, 5, 5, 'VIT', 'Cryptocurrency experts'),
('Ctrl Alt Defeat', 5, 5, 5, 'VIT', 'Defeating challenges'),
('Ctrl Alt Elite', 4, 4, 5, 'VIT', 'Elite control'),
('Ctrl+7', 5, 5, 5, 'VIT', 'Keyboard shortcuts'),
('Cyber sud', 4, 4, 5, 'VIT', 'Cybersecurity specialists'),
('Dawn Patrol', 4, 4, 5, 'VIT', 'Early morning coders'),
('Debug Thugs', 4, 4, 5, 'VIT', 'Debugging experts'),
('Dev Buddies', 4, 4, 5, 'VIT', 'Development buddies'),
('DevPunks', 2, 2, 5, 'VIT', 'Punk developers'),
('DoubleR', 2, 2, 5, 'VIT', 'Double R team'),
('Dun dees', 2, 2, 5, 'VIT', 'Dynamic duo'),
('Elite Coders (Team Elite)', 4, 4, 5, 'VIT', 'Elite coding team'),
('Error 404', 5, 5, 5, 'VIT', 'Error handling experts'),
('ERROR BREAKERS', 5, 5, 5, 'VIT', 'Error breaking team'),
('Express Files', 5, 5, 5, 'VIT', 'Express.js experts'),
('ExpressOPS', 5, 5, 5, 'VIT', 'Express operations'),
('F3', 3, 3, 5, 'VIT', 'F3 team'),
('Fidelity', 2, 2, 5, 'VIT', 'Fidelity in coding'),
('Future_frames', 1, 1, 5, 'VIT', 'Future-focused'),
('Genis', 2, 2, 5, 'VIT', 'Genesis team'),
('Gill Guad', 4, 4, 5, 'VIT', 'Gill Guad team'),
('Godlike', 5, 5, 5, 'VIT', 'Godlike performance'),
('GSolo', 1, 1, 5, 'VIT', 'Solo performer'),
('Gully Coders', 5, 5, 5, 'VIT', 'Gully coding style'),
('HACKON 5', 5, 5, 5, 'VIT', 'Hackathon veterans'),
('HackOps', 4, 4, 5, 'VIT', 'Hacking operations'),
('Hacksheet boys', 4, 4, 5, 'VIT', 'Hacksheet specialists'),
('HelloWorld', 5, 5, 5, 'VIT', 'Classic hello world'),
('Hunters', 2, 2, 5, 'VIT', 'Code hunters'),
('Hyper Brains', 3, 3, 5, 'VIT', 'Hyper intelligent'),
('Idea igniters', 4, 4, 5, 'VIT', 'Idea generation'),
('IMPROVECTS', 4, 4, 5, 'VIT', 'Improvement effects'),
('Infinite_loopers', 5, 5, 5, 'VIT', 'Infinite loop experts'),
('Inso Unity', 5, 5, 5, 'VIT', 'Unity in diversity'),
('Innov_8', 2, 2, 5, 'VIT', 'Innovation team'),
('Kamix', 5, 5, 5, 'VIT', 'Kamix team'),
('Kernel Crew', 5, 5, 5, 'VIT', 'Kernel specialists'),
('Kodoasira', 5, 5, 5, 'VIT', 'Kodoasira team'),
('LogicLayers', 3, 3, 5, 'VIT', 'Logic layer experts'),
('MothXAI', 4, 4, 5, 'VIT', 'AI specialists'),
('Meticulous Masterminds', 4, 4, 5, 'VIT', 'Meticulous approach'),
('Mystic Squad (Mystic Trio)', 3, 3, 5, 'VIT', 'Mystic trio'),
('Noobratwork', 3, 3, 5, 'VIT', 'Noob at work'),
('Nova Drift', 4, 4, 5, 'VIT', 'Nova drift team'),
('NU GEN', 3, 3, 5, 'VIT', 'New generation'),
('Panda', 5, 5, 5, 'VIT', 'Panda team'),
('Pirates of the Caribbean', 2, 2, 5, 'VIT', 'Pirate coding'),
('Pseudo Coders', 4, 4, 5, 'VIT', 'Pseudo coding'),
('PseudoSerpents', 4, 4, 5, 'VIT', 'Pseudo serpents'),
('QodX', 4, 4, 5, 'VIT', 'QodX team'),
('Quantum coders', 5, 5, 5, 'VIT', 'Quantum computing'),
('Quantum Coders (External)', 5, 5, 5, 'External', 'External quantum team'),
('React Racoons', 5, 5, 5, 'VIT', 'React specialists'),
('Shaktimaan', 5, 5, 5, 'VIT', 'Shaktimaan team'),
('ShaktiMaan', 5, 5, 5, 'VIT', 'ShaktiMaan team'),
('Skill issue', 5, 5, 5, 'VIT', 'Skill development'),
('Skyship', 4, 4, 5, 'VIT', 'Sky ship team'),
('SnakoBytes', 5, 5, 5, 'VIT', 'Snake bytes'),
('Spark', 5, 5, 5, 'VIT', 'Spark team'),
('SpiderCoders', 2, 2, 5, 'VIT', 'Spider coding'),
('Stack over achievers', 2, 2, 5, 'VIT', 'Stack overflow achievers'),
('StackForge', 5, 5, 5, 'VIT', 'Stack forging'),
('Stock', 1, 1, 5, 'VIT', 'Stock team'),
('Stranger string', 5, 5, 5, 'VIT', 'String manipulation'),
('Synapse', 3, 3, 5, 'VIT', 'Neural synapse'),
('Syntax Sages', 3, 3, 5, 'VIT', 'Syntax experts'),
('TEAM ELITE', 4, 4, 5, 'VIT', 'Elite team'),
('Team flanker', 3, 3, 5, 'VIT', 'Flanking team'),
('Team Nexus', 4, 4, 5, 'VIT', 'Nexus team'),
('Team Rocket', 3, 3, 5, 'VIT', 'Rocket team'),
('Team sols', 5, 5, 5, 'VIT', 'Solutions team'),
('Team UpsideDown', 2, 2, 5, 'VIT', 'Upside down approach'),
('Team Vaders', 5, 5, 5, 'VIT', 'Vader team'),
('Tech Jam', 4, 4, 5, 'VIT', 'Tech jam session'),
('TechGiants', 3, 3, 5, 'VIT', 'Tech giants'),
('Tesseract', 4, 4, 5, 'VIT', 'Tesseract team'),
('The Decrypters', 4, 4, 5, 'VIT', 'Decryption experts'),
('The Eighteens', 5, 5, 5, 'VIT', 'Eighteen team'),
('The Hackenings', 5, 5, 5, 'VIT', 'Hackening team'),
('The Kraken', 5, 5, 5, 'VIT', 'Kraken team'),
('The Optimizers', 5, 5, 5, 'VIT', 'Optimization experts'),
('The Orders', 4, 4, 5, 'VIT', 'Order team'),
('The Synergic Squad', 4, 4, 5, 'VIT', 'Synergic approach'),
('Tirtha Yatra', 4, 4, 5, 'VIT', 'Tirtha Yatra team'),
('Trailblazers', 2, 2, 5, 'VIT', 'Trailblazing team'),
('Tristack', 3, 3, 5, 'VIT', 'Three stack team'),
('Trojan Bots', 4, 4, 5, 'VIT', 'Trojan bot team'),
('VAQ-U', 3, 3, 5, 'VIT', 'VAQ-U team'),
('Vector', 4, 4, 5, 'VIT', 'Vector team'),
('Vision X', 5, 5, 5, 'VIT', 'Vision X team'),
('Visionary', 3, 3, 5, 'VIT', 'Visionary team'),
('While(0)(Deafeat)', 5, 5, 5, 'VIT', 'While loop team'),
('Why-o''s Fault', 4, 4, 5, 'VIT', 'Why-o fault team'),
('Zenith', 6, 5, 5, 'VIT', 'Peak performance team'),

-- Teams with 0 points (did not complete or submit)
('#07 club', 4, 1, 0, 'VIT', 'Incomplete submission'),
('ACTIVE LEARNERS', 2, 1, 0, 'VIT', 'No submission'),
('Aegris', 4, 1, 0, 'VIT', 'Incomplete'),
('Byte Bandits', 5, 3, 0, 'VIT', 'Did not finish'),
('CODE SLAYERS', 4, 3, 0, 'VIT', 'Did not complete'),
('Code-Edge', 5, 4, 0, 'VIT', 'Incomplete submission'),
('Dawn Town Coders', 4, 3, 0, 'VIT', 'Did not complete'),
('Dynamic coders', 5, 1, 0, 'VIT', 'Incomplete'),
('Fusion murder', 4, 1, 0, 'VIT', 'Did not finish'),
('FUSION MASTERS', 4, 3, 0, 'VIT', 'Incomplete submission'),
('Igniters', 5, 4, 0, 'VIT', 'Did not complete'),
('Infinite Binary', 5, 4, 0, 'VIT', 'Incomplete'),
('Kabhi Khushi Kabhi Gham', 5, 1, 0, 'VIT', 'Did not finish'),
('Mad Coders', 5, 4, 0, 'VIT', 'Incomplete submission'),
('Narayani Sena', 5, 4, 0, 'VIT', 'Did not complete'),
('Neuralink', 5, 5, 0, 'VIT', 'Incomplete'),
('Noob Hackers', 4, 2, 0, 'VIT', 'No submission'),
('Polalo Coders', 4, 4, 0, 'VIT', 'Did not finish'),
('Runtime Terror', 5, 4, 0, 'VIT', 'Incomplete submission'),
('ShoUnit', 5, 4, 0, 'VIT', 'Did not complete'),
('Solution Seekers', 4, 3, 0, 'VIT', 'Incomplete'),
('Spark plug', 5, 2, 0, 'VIT', 'Did not finish'),
('TASQB', 5, 4, 0, 'VIT', 'Incomplete submission'),
('Team Neuralink', 5, 1, 0, 'VIT', 'Did not complete'),
('Team XYZ', 3, 2, 0, 'VIT', 'Incomplete'),
('The Codesmokers', 5, 2, 0, 'VIT', 'Did not finish'),
('XYZ', 3, 1, 0, 'VIT', 'No submission'),

-- Special case with calculation error
('Code hunt', 3, 0, 0, 'VIT', 'Calculation error - needs review')

ON CONFLICT (team_name) DO UPDATE SET
    total_members = EXCLUDED.total_members,
    linkedin_posts = EXCLUDED.linkedin_posts,
    round1_points = EXCLUDED.round1_points,
    team_type = EXCLUDED.team_type,
    notes = EXCLUDED.notes,
    updated_at = CURRENT_TIMESTAMP;

-- Verify the data was inserted correctly
SELECT 
    COUNT(*) as total_teams,
    COUNT(CASE WHEN round1_points = 5 THEN 1 END) as successful_teams,
    COUNT(CASE WHEN round1_points = 0 THEN 1 END) as incomplete_teams,
    COUNT(CASE WHEN team_type = 'VIT' THEN 1 END) as vit_teams,
    COUNT(CASE WHEN team_type = 'External' THEN 1 END) as external_teams
FROM leaderboard;

-- Show top 20 teams
SELECT 
    team_name,
    total_members,
    linkedin_posts,
    round1_points,
    total_points,
    team_type
FROM leaderboard 
ORDER BY total_points DESC, round1_points DESC 
LIMIT 20;
